demo:
  data:
    dataSource:
      # 使用druid数据源
      defaultDataSourceType: com.alibaba.druid.pool.DruidDataSource
      defaultDriverClassName: com.mysql.jdbc.Driver
      # 具体配置
      dataSourceItems:
        - master: true
          name: master
          url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&rewriterBatchedStatements=true
          username: root
          password: kwang950208
        - master: false
          name: slave
          url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&rewriterBatchedStatements=true
          username: root
          password: kwang950208

    mybatis:
      base-package: com.example.demo.persist.mapper
      type-aliases-package: com.example.demo.persist.entity
      identity: MYSQL
      mapper-locations: classpath*:mapper/**/*.xml
      check-config-location: false
      not-empty: false
      mappers: com.example.demo.mybatis.bean.IMapper
      config: mybatis-config.xml

    redis:
      main:
        #password:
        timeout: 50000
        expire-seconds: 1800
        pool-max-idle: 100
        pool-max-total: 500
        pool-max-wait-millis: 10000
        pool-min-idle: 50
        #单机配置
        host: 127.0.0.1
        port: 6379
        #集群配置
        #sentinel-master: redis01
        #sentinel-nodes: 127.0.0.1:6379，127.0.0.2:6379

    mongodb:
      #username: root
      #password: 123456
      default-database: mydb
      connection-per-host: 100
      connection-timeout: 30000
      max-wait-time: 30000
      hosts: 10.168.158.250:27017,10.168.159.3:27017


#my-props:
#  simpleProp: simplePropValue
#  arrayProps: 1,2,3,4,5
#  listProp1:
#    - name: abc
#      value: abcValue
#    - name: efg
#      value: efgValue
#  listProp2:
#    - config2Value1
#    - config2Vavlue2
#  mapProps:
#    key1: value1
#    key2: value2
#
#
#mamahao:
#  data:
#    redis:
#      - out: 50000
#        expire: 1800
#        max: 100
#        total: 500
#        wait: 10000
#        min: 50
#        master: redis01
#        nodes: 10.117.42.229:6379,10.168.10.66:6379
#      - out: 50000
#        expire: 1800
#        max: 100
#        total: 500
#        wait: 10000
#        min: 50
#        master: redis02
#        nodes: 20.117.42.229:6379,20.168.10.66:6379
#
#logging:
#  level:
#    org.springframework.web: ERROR
#    com.yiibai: DEBUG
#email: test@yiibai.com
#thread-pool: 10
#app:
#  menus:
#    - title: Home
#      name: Home
#      path: /
#    - title: Login
#      name: Login
#      path: /login
#  compiler:
#    timeout: 5
#    output-folder: /temp/
#  error: /error/
#
#
#
#test:
#  data:
#    redis:
#      - timeout: 1
#        expire_seconds: 500
#        title: Home
#        name: Home
#        path: /
#      - timeout: 2
#        expire_seconds: 500
#        title: Login
#        name: Login
#        path: /login
#    compiler:
#      timeout: 5
#      output-folder: /temp/
#    error: /error/
#
#
#mamahao:
#  data:
#    redis:
#      - timeout: 50000
#        expire_seconds: 1800
#        pool-max-idle: 100
#        pool-max-total: 500
#        pool-max-wait-millis: 10000
#        pool-min-idle: 50
#        sentinel-master: redis01
#        sentinel-nodes: 10.117.42.229:6379,10.168.10.66:6379
#      - timeout: 50000
#        expire_seconds: 1800
#        pool-max-idle: 100
#        pool-max-total: 500
#        pool-max-wait-millis: 10000
#        pool-min-idle: 50
#        sentinel-master: redis02
#        sentinel-nodes: 10.117.42.229:6379,10.168.10.66:6379
#
#data:
#  test:
#    redis:
#        timeout: 50000
#        expire_seconds: 1800
#        pool-max-idle: 100
#        pool-max-total: 500
#        pool-max-wait-millis: 10000
#        pool-min-idle: 50
#        sentinel-master: redis01
#        sentinel-nodes: 10.117.42.229:6379,10.168.10.66:6379
#    redis-act:
#        timeout: 50000
#        expire_seconds: 1800
#        pool-max-idle: 100
#        pool-max-total: 500
#        pool-max-wait-millis: 10000
#        pool-min-idle: 50
#        sentinel-master: redis02
#        sentinel-nodes: 10.117.42.229:6379,10.168.10.66:6379
