demo:
  data:
    dataSource:
      defaultDataSourceType: com.alibaba.druid.pool.DruidDataSource
      defaultDriverClassName: com.mysql.jdbc.Driver
      autoSwitchDataSource: true
    mybatis:
      base-package: com.example.demo.persist.mapper
      type-aliases-package: com.example.demo.persist.entity
      identity: MYSQL
      mapper-locations: classpath*:mapper/**/*.xml
      check-config-location: false
      not-empty: false
#      mappers: .IMapper
      config: mybatis-config.xml
    mongodb:
          default-database: mydb

#my-props:
#  simpleProp: simplePropValue
#  arrayProps: 1,2,3,4,5
#  listProp1:
#    - name: abc
#      value: abcValue
#    - name: efg
#      value: efgValue
#  listProp2:
#    - config2Value1
#    - config2Vavlue2
#  mapProps:
#    key1: value1
#    key2: value2
#
#
#mamahao:
#  data:
#    redis:
#      - out: 50000
#        expire: 1800
#        max: 100
#        total: 500
#        wait: 10000
#        min: 50
#        master: redis01
#        nodes: 10.117.42.229:6379,10.168.10.66:6379
#      - out: 50000
#        expire: 1800
#        max: 100
#        total: 500
#        wait: 10000
#        min: 50
#        master: redis02
#        nodes: 20.117.42.229:6379,20.168.10.66:6379
#
#logging:
#  level:
#    org.springframework.web: ERROR
#    com.yiibai: DEBUG
#email: test@yiibai.com
#thread-pool: 10
#app:
#  menus:
#    - title: Home
#      name: Home
#      path: /
#    - title: Login
#      name: Login
#      path: /login
#  compiler:
#    timeout: 5
#    output-folder: /temp/
#  error: /error/
#
#
#
#test:
#  data:
#    redis:
#      - timeout: 1
#        expire_seconds: 500
#        title: Home
#        name: Home
#        path: /
#      - timeout: 2
#        expire_seconds: 500
#        title: Login
#        name: Login
#        path: /login
#    compiler:
#      timeout: 5
#      output-folder: /temp/
#    error: /error/
#
#
#mamahao:
#  data:
#    redis:
#      - timeout: 50000
#        expire_seconds: 1800
#        pool-max-idle: 100
#        pool-max-total: 500
#        pool-max-wait-millis: 10000
#        pool-min-idle: 50
#        sentinel-master: redis01
#        sentinel-nodes: 10.117.42.229:6379,10.168.10.66:6379
#      - timeout: 50000
#        expire_seconds: 1800
#        pool-max-idle: 100
#        pool-max-total: 500
#        pool-max-wait-millis: 10000
#        pool-min-idle: 50
#        sentinel-master: redis02
#        sentinel-nodes: 10.117.42.229:6379,10.168.10.66:6379
#
#data:
#  test:
#    redis:
#        timeout: 50000
#        expire_seconds: 1800
#        pool-max-idle: 100
#        pool-max-total: 500
#        pool-max-wait-millis: 10000
#        pool-min-idle: 50
#        sentinel-master: redis01
#        sentinel-nodes: 10.117.42.229:6379,10.168.10.66:6379
#    redis-act:
#        timeout: 50000
#        expire_seconds: 1800
#        pool-max-idle: 100
#        pool-max-total: 500
#        pool-max-wait-millis: 10000
#        pool-min-idle: 50
#        sentinel-master: redis02
#        sentinel-nodes: 10.117.42.229:6379,10.168.10.66:6379
